from django.db import models


# Create your models here.
class SsqInfo(models.Model):
    # 开奖期数
    number = models.CharField(4)

    red01 = models.CharField(4)
    red02 = models.CharField(4)
    red03 = models.CharField(4)
    red04 = models.CharField(4)
    red05 = models.CharField(4)
    red06 = models.CharField(4)
    red07 = models.CharField(4)
    red08 = models.CharField(4)
    red09 = models.CharField(4)
    red10 = models.CharField(4)
    red11 = models.CharField(4)
    red12 = models.CharField(4)
    red13 = models.CharField(4)
    red14 = models.CharField(4)
    red15 = models.CharField(4)
    red16 = models.CharField(4)
    red17 = models.CharField(4)
    red18 = models.CharField(4)
    red19 = models.CharField(4)
    red20 = models.CharField(4)
    red21 = models.CharField(4)
    red22 = models.CharField(4)
    red23 = models.CharField(4)
    red24 = models.CharField(4)
    red25 = models.CharField(4)
    red26 = models.CharField(4)
    red27 = models.CharField(4)
    red28 = models.CharField(4)
    red29 = models.CharField(4)
    red30 = models.CharField(4)
    red31 = models.CharField(4)
    red32 = models.CharField(4)
    red33 = models.CharField(4)

    blue01 = models.CharField(4)
    blue02 = models.CharField(4)
    blue03 = models.CharField(4)
    blue04 = models.CharField(4)
    blue05 = models.CharField(4)
    blue06 = models.CharField(4)
    blue07 = models.CharField(4)
    blue08 = models.CharField(4)
    blue09 = models.CharField(4)
    blue10 = models.CharField(4)
    blue11 = models.CharField(4)
    blue12 = models.CharField(4)
    blue13 = models.CharField(4)
    blue14 = models.CharField(4)
    blue15 = models.CharField(4)
    blue16 = models.CharField(4)
