# Generated by Django 2.1b1 on 2018-07-09 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssq_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ssqtest',
            fields=[
                ('number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('red1', models.CharField(max_length=2)),
                ('red2', models.CharField(max_length=2)),
                ('red3', models.CharField(max_length=2)),
                ('red4', models.CharField(max_length=2)),
            ],
        ),
    ]
